In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#we have 21 cols only so this is safe-ish
pd.set_option('display.max_columns', None)

In [16]:
data = pd.read_csv("../../data/train.csv")

# basic EDA

In [17]:
data.columns

Index(['id', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

no time dependencies

In [18]:
data.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,No,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,Yes,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [19]:
#any NaNs at all or is this super clean?

In [21]:
data.tail()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
594189,594189,Male,0,No,No,57,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),97.55,5460.70,No
594190,594190,Female,0,No,No,72,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),91.95,6782.15,No
594191,594191,Female,0,Yes,No,72,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.40,1871.90,No
594192,594192,Female,0,No,No,32,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,86.00,2847.20,No
594193,594193,Female,1,Yes,No,2,Yes,No,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,54.55,108.05,Yes

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

In [36]:
#no NaNs

In [37]:
for col in data.columns:
    if col != "id":
        print(f"{col} col {data[col].value_counts()}\n")

gender col gender
Female    298738
Male      295456
Name: count, dtype: int64

SeniorCitizen col SeniorCitizen
0    526395
1     67799
Name: count, dtype: int64

Partner col Partner
Yes    309554
No     284640
Name: count, dtype: int64

Dependents col Dependents
No     414362
Yes    179832
Name: count, dtype: int64

tenure col tenure
72    56411
1     29182
71    20763
2     16766
3     13478
      ...
40     4203
21     3862
44     3496
39     3396
36     2562
Name: count, Length: 72, dtype: int64

PhoneService col PhoneService
Yes    557893
No      36301
Name: count, dtype: int64

MultipleLines col MultipleLines
No                  283384
Yes                 274509
No phone service     36301
Name: count, dtype: int64

InternetService col InternetService
Fiber optic    272386
DSL            181081
No             140727
Name: count, dtype: int64

OnlineSecurity col OnlineSecurity
No                     289474
Yes                    163993
No internet service    140727
Name: count, dtype: int64

OnlineBackup col OnlineBackup
No                     250083
Yes                    203384
No internet service    140727
Name: count, dtype: int64

DeviceProtection col DeviceProtection
No                     247377
Yes                    206090
No internet service    140727
Name: count, dtype: int64

TechSupport col TechSupport
No                     288571
Yes                    164896
No internet service    140727
Name: count, dtype: int64

StreamingTV col StreamingTV
Yes                    240301
No                     213166
No internet service    140727
Name: count, dtype: int64

StreamingMovies col StreamingMovies
Yes                    241435
No                     212032
No internet service    140727
Name: count, dtype: int64

Contract col Contract
Month-to-month    298918
Two year          186943
One year          108333
Name: count, dtype: int64

PaperlessBilling col PaperlessBilling
Yes    365579
No     228615
Name: count, dtype: int64

PaymentMethod col PaymentMethod
Electronic check             215372
Credit card (automatic)      133705
Mailed check                 123757
Bank transfer (automatic)    121360
Name: count, dtype: int64

MonthlyCharges col MonthlyCharges
20.05    7436
19.95    5718
19.70    5705
20.00    5493
19.85    5114
         ...
28.95       1
89.24       1
94.96       1
37.25       1
46.15       1
Name: count, Length: 1921, dtype: int64

TotalCharges col TotalCharges
6096.90    850
1110.05    846
6448.05    734
854.90     721
7133.25    619
          ...
1564.35      1
1483.05      1
491.10       1
6419.90      1
5460.70      1
Name: count, Length: 31910, dtype: int64

Churn col Churn
No     460377
Yes    133817
Name: count, dtype: int64

no data cleaning needed